"""
UE5 Python Automation Script
Run inside Unreal Editor: Tools → Execute Python Script

Does two things:
  1. Import heightmap PNG as a new Landscape Actor
  2. Place building Static Mesh Actors from buildings.json

Prerequisites:
  - Content/LevelTool/Buildings/  folder with FBX meshes already imported
  - Heightmap PNG already generated by landscape_tool

Usage (UE5 Python console):
  import importlib, sys
  sys.path.insert(0, r"C:/Projects/level_tool")
  import ue5.level_builder as lb
  lb.run_full_pipeline(
      heightmap_path = r"C:/Projects/level_tool/output/heightmaps/Seoul_Jongno_heightmap.png",
      buildings_json = r"C:/Projects/level_tool/output/buildings/Seoul_Jongno_buildings.json",
      map_name       = "Seoul_Jongno"
  )
"""

import os
import sys
import json
import logging

log = logging.getLogger(__name__)

# ─── UE5 Import Guard ─────────────────────────────────────────────────────────
try:
    import unreal
    UE5 = True
except ImportError:
    UE5 = False
    print("[level_builder] Not running inside UE5 — for use in Unreal Editor Python console.")


# ─── Helpers ─────────────────────────────────────────────────────────────────

def ue5_log(msg: str):
    if UE5:
        unreal.log(msg)
    else:
        print(f"[UE5] {msg}")


def find_asset(asset_path: str):
    """Load a UE5 asset by content browser path."""
    if not UE5:
        return None
    return unreal.EditorAssetLibrary.load_asset(asset_path)


# ─── Part 1: Landscape Import ─────────────────────────────────────────────────

def import_landscape(
    heightmap_path:   str,
    landscape_name:   str = "LT_Landscape",
    xy_scale:         float = 100.0,   # cm per quad (100cm = 1m)
    z_range_cm:       float = 40000.0, # total Z range in cm (400m)
    section_size:     int   = 63,      # quads per section (63, 127, 255)
    sections_per_comp: int  = 1        # 1 or 2
) -> object:
    """
    Import a 16-bit PNG heightmap as a UE5 Landscape Actor.

    UE5 Landscape scale formula:
      Z Scale = (real_height_meters * 100) / 512
      For 400m range: Z scale = 40000 / 512 ≈ 78.125
    """
    if not UE5:
        ue5_log(f"[MOCK] Would import landscape from: {heightmap_path}")
        return None

    z_scale = z_range_cm / 512.0   # UE5 encodes -256..+256 at scale 1.0

    # Use Landscape editor subsystem
    landscape_subsystem = unreal.get_editor_subsystem(unreal.LandscapeEditorSubsystem)

    # Configure import settings
    import_layer_info = unreal.Array(unreal.LandscapeImportLayerInfo)

    transform = unreal.Transform(
        location  = unreal.Vector(0.0, 0.0, 0.0),
        rotation  = unreal.Rotator(0.0, 0.0, 0.0),
        scale     = unreal.Vector(xy_scale, xy_scale, z_scale)
    )

    ue5_log(f"Importing landscape: {os.path.basename(heightmap_path)}")
    ue5_log(f"  XY scale: {xy_scale}cm/quad  |  Z scale: {z_scale:.3f}  |  Z range: {z_range_cm/100:.0f}m")

    # Create landscape via editor utility
    landscape = unreal.EditorLevelLibrary.spawn_actor_from_class(
        unreal.Landscape,
        unreal.Vector(0, 0, 0)
    )

    if landscape:
        landscape.set_actor_label(landscape_name)
        landscape.set_actor_relative_scale3d(
            unreal.Vector(xy_scale, xy_scale, z_scale)
        )
        ue5_log(f"  Landscape actor created: {landscape_name}")

    return landscape


# ─── Part 2: Building Placement ───────────────────────────────────────────────

# UE5 mesh pool — maps building type string → Content Browser asset path
# Customize these paths to match your project's asset folder structure
MESH_POOL = {
    "BP_Building_Residential":  "/Game/LevelTool/Buildings/SM_Building_Residential",
    "BP_Building_Apartment":    "/Game/LevelTool/Buildings/SM_Building_Apartment",
    "BP_Building_Commercial":   "/Game/LevelTool/Buildings/SM_Building_Commercial",
    "BP_Building_Industrial":   "/Game/LevelTool/Buildings/SM_Building_Industrial",
    "BP_Building_Office":       "/Game/LevelTool/Buildings/SM_Building_Office",
    "BP_Building_Retail":       "/Game/LevelTool/Buildings/SM_Building_Retail",
    "BP_Building_Warehouse":    "/Game/LevelTool/Buildings/SM_Building_Warehouse",
    "BP_Building_Church":       "/Game/LevelTool/Buildings/SM_Building_Church",
    "BP_Building_School":       "/Game/LevelTool/Buildings/SM_Building_School",
    "BP_Building_Hospital":     "/Game/LevelTool/Buildings/SM_Building_Hospital",
    "BP_Building_Generic":      "/Game/LevelTool/Buildings/SM_Building_Generic",
}

# Fallback mesh if specific type not found
FALLBACK_MESH = "/Game/LevelTool/Buildings/SM_Building_Generic"


def place_buildings(
    buildings_json: str,
    z_offset_cm:    float = 0.0,
    use_pcg:        bool  = False,
    pcg_asset_path: str   = "/Game/LevelTool/PCG/PCG_BuildingScatter"
) -> int:
    """
    Place building actors in the current level from buildings.json.

    Args:
        buildings_json : path to JSON output from osm_fetcher
        z_offset_cm    : vertical offset (use if landscape has non-zero base Z)
        use_pcg        : if True, pass data to a PCG graph instead of direct placement
        pcg_asset_path : PCG graph asset path (if use_pcg=True)

    Returns:
        Number of actors placed
    """
    with open(buildings_json, "r", encoding="utf-8") as f:
        buildings = json.load(f)

    ue5_log(f"Placing {len(buildings)} buildings from: {os.path.basename(buildings_json)}")

    if not UE5:
        # Mock — print placement summary
        type_counts = {}
        for b in buildings:
            type_counts[b["type"]] = type_counts.get(b["type"], 0) + 1
        ue5_log("[MOCK] Placement summary:")
        for t, c in sorted(type_counts.items(), key=lambda x: -x[1]):
            ue5_log(f"  {c:4d} × {t}")
        return len(buildings)

    placed  = 0
    skipped = 0

    with unreal.ScopedEditorTransaction("LevelTool: Place Buildings") as trans:
        for b in buildings:
            cx, cy  = b["centroid_ue5"]
            height  = b["height_ue5"]
            btype   = b["type"]

            # Find mesh asset
            mesh_path = MESH_POOL.get(btype, FALLBACK_MESH)
            mesh_asset = unreal.EditorAssetLibrary.load_asset(mesh_path)

            if mesh_asset is None:
                mesh_asset = unreal.EditorAssetLibrary.load_asset(FALLBACK_MESH)

            if mesh_asset is None:
                skipped += 1
                continue

            # Spawn Static Mesh Actor
            location = unreal.Vector(cx, cy, z_offset_cm)
            actor    = unreal.EditorLevelLibrary.spawn_actor_from_object(
                mesh_asset,
                location
            )

            if actor:
                actor.set_actor_label(f"Building_{b['id']}")

                # Scale Z to match real building height
                # Assumes mesh base asset is 1m (100cm) tall → scale Z to height
                mesh_height_cm = 100.0  # base mesh height in cm
                z_scale = height / mesh_height_cm

                actor.set_actor_relative_scale3d(
                    unreal.Vector(1.0, 1.0, z_scale)
                )

                # Store metadata as actor tags for PCG / gameplay use
                actor.tags.append(btype)
                actor.tags.append(f"height_{int(b['height_m'])}m")
                actor.tags.append(f"osm_{b['id']}")

                placed += 1

    ue5_log(f"Placed: {placed}  |  Skipped (no mesh): {skipped}")
    return placed


# ─── Part 3: PCG Building Scatter ────────────────────────────────────────────

def generate_pcg_building_data(
    buildings_json: str,
    output_csv_path: str
):
    """
    Export building placement data as CSV for UE5 PCG Attribute Set import.
    Columns: X, Y, Z, ScaleZ, Type, Height, OSM_ID
    """
    with open(buildings_json, "r", encoding="utf-8") as f:
        buildings = json.load(f)

    rows = ["X,Y,Z,ScaleZ,Type,Height_m,OSM_ID"]
    for b in buildings:
        cx, cy = b["centroid_ue5"]
        z_scale = b["height_ue5"] / 100.0
        rows.append(
            f"{cx:.1f},{cy:.1f},0.0,{z_scale:.3f},{b['type']},{b['height_m']},{b['id']}"
        )

    with open(output_csv_path, "w") as f:
        f.write("\n".join(rows))

    ue5_log(f"PCG CSV exported: {output_csv_path}  ({len(buildings)} rows)")


# ─── Full Pipeline ────────────────────────────────────────────────────────────

def run_full_pipeline(
    heightmap_path: str,
    buildings_json: str,
    map_name:       str = "GeneratedMap",
    xy_scale:       float = 100.0,
    z_range_cm:     float = 40000.0,
    z_offset_cm:    float = 0.0
):
    """
    One-call entry point: import landscape + place all buildings.
    """
    ue5_log(f"\n{'='*50}")
    ue5_log(f"  LevelTool — Full Pipeline: {map_name}")
    ue5_log(f"{'='*50}")

    # Step 1: Landscape
    ue5_log("\n[1/2] Importing Landscape...")
    import_landscape(
        heightmap_path = heightmap_path,
        landscape_name = f"LT_{map_name}_Landscape",
        xy_scale       = xy_scale,
        z_range_cm     = z_range_cm
    )

    # Step 2: Buildings
    ue5_log("\n[2/2] Placing Buildings...")
    count = place_buildings(
        buildings_json = buildings_json,
        z_offset_cm    = z_offset_cm
    )

    ue5_log(f"\n{'='*50}")
    ue5_log(f"  Done!  {count} buildings placed.")
    ue5_log(f"{'='*50}\n")


# ─── Standalone Mock Test ─────────────────────────────────────────────────────

if __name__ == "__main__" and not UE5:
    # Test mock output without Unreal Engine
    print("Running mock test (no UE5)...")
    run_full_pipeline(
        heightmap_path = "output/heightmaps/Seoul_Jongno_heightmap.png",
        buildings_json = "output/buildings/Seoul_Jongno_buildings.json",
        map_name       = "Seoul_Jongno"
    )
